global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter_scrape'
    static_configs:
    - targets: ['app-node-exporter:9100']
      labels:
        instance: 'Local Server'
        host: '127.0.9.1'
        node: 'local'
